import e1 from "../assets/e1.png";
import ai from "../assets/ai.png";
import trans from "../assets/trans.png";
import excel from "../assets/excel.png";
import b1 from "../assets/b1.png";
import amp from "../assets/amp.png";
import r1 from "../assets/r1.png";
import r2 from "../assets/r2.png";

export const navItems = [
  { value: "Home", path: "/" },
  { value: "About Us", path: "/about-us" },
  { value: "Services", path: "/services" },
  { value: "Blogs", path: "/blogs" },
  { value: "Contact Us", path: "/contact-us" },
];

export const services = [
  {
    name: "Transparency",
    pic: trans,
    text: "ieajsfowe eijfk wea oawe v oie oigrejd owrejnij gieiji eirh igerh iwgwo hreih ",
  },
  {
    name: "Stem Based Ai Solution",
    pic: ai,
    text: "ieajsfowe eijfk wea oawe v oie oigrejd owrejnij gieiji eirh igerh iwgwo hreih ",
  },
  {
    name: "Excellent customer support",
    pic: excel,
    text: "ieajsfowe eijfk wea oawe v oie oigrejd owrejnij gieiji eirh igerh iwgwo hreih ",
  },
];

export const blogs = [
  {
    name: "Empowering The Paralyzed",
    pic: b1,
    text: "ieajsfowe eijfk wea oawe v oie oigrejd owrejnij gieiji eirh igerh iwgwo hreih ",
  },
  {
    name: "Silent Sepectator",
    pic: amp,
    text: "ieajsfowe eijfk wea oawe v oie oigrejd owrejnij gieiji eirh igerh iwgwo hreih ",
  },
];

export const vision = [
  {
    pic: e1,
    text: "Lorem ipsum dolor sit amet consectetur adip",
  },
  {
    pic: e1,
    text: "Lorem ipsum dolor sit amet consectetur adip",
  },
];

export const social = [
  {
    pic: r1,
    link: "/",
  },
  {
    pic: r2,
    link: "/",
  },
];

export const series = [
  {
    name: "Pioneering Voices",
    blogs: [
      {
        name: "Empowering The Paralyzed",
        pic: b1,
        data: "In the realm of sports, a world of excitement, celebration, and unity unfolds. Mega sports events, such as “The Cricket World Cup”, have the remarkable power to bring together billions of people from diverse backgrounds, transcending language barriers, cultural differences, and national boundaries. These events infuse an unparalleled level of energy and enthusiasm among fans of the game . The love for cricket is an undisputed passion, irrespective of one's personal abilities and circumstances. Every spectator, regardless of their physical capabilities, experiences a profound sense of joy and boundless energy while supporting their team during the tournament.This sentiment extends even to those who may not have the same physical mobility as others, including individuals who are paralyzed. In the context of empowering differently-abled individuals and making their lives more fulfilling during events like the World Cup, it's crucial to highlight the government's efforts and available resources. In 2022-23, the Department of Empowerment of Persons with Disabilities (DEPwD) received a significant budget allocation of Rs 1212.41 crore, reflecting a positive trend of increasing support for differently abled community. This financial boost indicates a growing recognition of the importance of inclusion and accessibility for all, regardless of physical abilities. Paralyzed people make a significant portion of the society that make most of all the opportunities given to them and utilize available resources to navigate through the events and find joy as enthusiastic audience. The Deendayal Disabled Rehabilitation Scheme (DDRS) is a vital initiative under the DEPwD that aims to promote voluntary action for persons with disabilities. This scheme provides essential support, rehabilitation services and assistive devices, contributing to a better quality of life for physically impaired individuals. These extraordinary individuals impart invaluable life lessons to us. They exemplify the resilience needed to overcome obstacles and demonstrate that no matter how insurmountable the challenges may seem, there is always a motivating force compelling us to rise above our problems. Moreover, it is the responsibility of those who possess physical capabilities to extend a helping hand to those in need, opening the doors of our hearts as wide as possible.",
      },
      {
        name: "Silent Spectator: Journey of an Indian Cricket Fan",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
    ],
  },
  {
    name: "Triumph Tales",
    blogs: [
      {
        name: "Comming Soon",
        pic: amp,
        data: "In the realm of sports, a world of excitement, celebration, and unity unfolds. Mega sports events, such as “The Cricket World Cup”, have the remarkable power to bring together billions of people from diverse backgrounds, transcending language barriers, cultural differences, and national boundaries. These events infuse an unparalleled level of energy and enthusiasm among fans of the game . The love for cricket is an undisputed passion, irrespective of one's personal abilities and circumstances. Every spectator, regardless of their physical capabilities, experiences a profound sense of joy and boundless energy while supporting their team during the tournament.This sentiment extends even to those who may not have the same physical mobility as others, including individuals who are paralyzed. In the context of empowering differently-abled individuals and making their lives more fulfilling during events like the World Cup, it's crucial to highlight the government's efforts and available resources. In 2022-23, the Department of Empowerment of Persons with Disabilities (DEPwD) received a significant budget allocation of Rs 1212.41 crore, reflecting a positive trend of increasing support for differently abled community. This financial boost indicates a growing recognition of the importance of inclusion and accessibility for all, regardless of physical abilities. Paralyzed people make a significant portion of the society that make most of all the opportunities given to them and utilize available resources to navigate through the events and find joy as enthusiastic audience. The Deendayal Disabled Rehabilitation Scheme (DDRS) is a vital initiative under the DEPwD that aims to promote voluntary action for persons with disabilities. This scheme provides essential support, rehabilitation services and assistive devices, contributing to a better quality of life for physically impaired individuals. These extraordinary individuals impart invaluable life lessons to us. They exemplify the resilience needed to overcome obstacles and demonstrate that no matter how insurmountable the challenges may seem, there is always a motivating force compelling us to rise above our problems. Moreover, it is the responsibility of those who possess physical capabilities to extend a helping hand to those in need, opening the doors of our hearts as wide as possible.",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
    ],
  },
  {
    name: "Comming Soon",
    blogs: [
      {
        name: "Comming Soon",
        pic: amp,
        data: "In the realm of sports, a world of excitement, celebration, and unity unfolds. Mega sports events, such as “The Cricket World Cup”, have the remarkable power to bring together billions of people from diverse backgrounds, transcending language barriers, cultural differences, and national boundaries. These events infuse an unparalleled level of energy and enthusiasm among fans of the game . The love for cricket is an undisputed passion, irrespective of one's personal abilities and circumstances. Every spectator, regardless of their physical capabilities, experiences a profound sense of joy and boundless energy while supporting their team during the tournament.This sentiment extends even to those who may not have the same physical mobility as others, including individuals who are paralyzed. In the context of empowering differently-abled individuals and making their lives more fulfilling during events like the World Cup, it's crucial to highlight the government's efforts and available resources. In 2022-23, the Department of Empowerment of Persons with Disabilities (DEPwD) received a significant budget allocation of Rs 1212.41 crore, reflecting a positive trend of increasing support for differently abled community. This financial boost indicates a growing recognition of the importance of inclusion and accessibility for all, regardless of physical abilities. Paralyzed people make a significant portion of the society that make most of all the opportunities given to them and utilize available resources to navigate through the events and find joy as enthusiastic audience. The Deendayal Disabled Rehabilitation Scheme (DDRS) is a vital initiative under the DEPwD that aims to promote voluntary action for persons with disabilities. This scheme provides essential support, rehabilitation services and assistive devices, contributing to a better quality of life for physically impaired individuals. These extraordinary individuals impart invaluable life lessons to us. They exemplify the resilience needed to overcome obstacles and demonstrate that no matter how insurmountable the challenges may seem, there is always a motivating force compelling us to rise above our problems. Moreover, it is the responsibility of those who possess physical capabilities to extend a helping hand to those in need, opening the doors of our hearts as wide as possible.",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
    ],
  },
  {
    name: "Comming Soon",
    blogs: [
      {
        name: "Comming Soon",
        pic: amp,
        data: "In the realm of sports, a world of excitement, celebration, and unity unfolds. Mega sports events, such as “The Cricket World Cup”, have the remarkable power to bring together billions of people from diverse backgrounds, transcending language barriers, cultural differences, and national boundaries. These events infuse an unparalleled level of energy and enthusiasm among fans of the game . The love for cricket is an undisputed passion, irrespective of one's personal abilities and circumstances. Every spectator, regardless of their physical capabilities, experiences a profound sense of joy and boundless energy while supporting their team during the tournament.This sentiment extends even to those who may not have the same physical mobility as others, including individuals who are paralyzed. In the context of empowering differently-abled individuals and making their lives more fulfilling during events like the World Cup, it's crucial to highlight the government's efforts and available resources. In 2022-23, the Department of Empowerment of Persons with Disabilities (DEPwD) received a significant budget allocation of Rs 1212.41 crore, reflecting a positive trend of increasing support for differently abled community. This financial boost indicates a growing recognition of the importance of inclusion and accessibility for all, regardless of physical abilities. Paralyzed people make a significant portion of the society that make most of all the opportunities given to them and utilize available resources to navigate through the events and find joy as enthusiastic audience. The Deendayal Disabled Rehabilitation Scheme (DDRS) is a vital initiative under the DEPwD that aims to promote voluntary action for persons with disabilities. This scheme provides essential support, rehabilitation services and assistive devices, contributing to a better quality of life for physically impaired individuals. These extraordinary individuals impart invaluable life lessons to us. They exemplify the resilience needed to overcome obstacles and demonstrate that no matter how insurmountable the challenges may seem, there is always a motivating force compelling us to rise above our problems. Moreover, it is the responsibility of those who possess physical capabilities to extend a helping hand to those in need, opening the doors of our hearts as wide as possible.",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
    ],
  },
  {
    name: "Comming Soon",
    blogs: [
      {
        name: "Comming Soon",
        pic: amp,
        data: "In the realm of sports, a world of excitement, celebration, and unity unfolds. Mega sports events, such as “The Cricket World Cup”, have the remarkable power to bring together billions of people from diverse backgrounds, transcending language barriers, cultural differences, and national boundaries. These events infuse an unparalleled level of energy and enthusiasm among fans of the game . The love for cricket is an undisputed passion, irrespective of one's personal abilities and circumstances. Every spectator, regardless of their physical capabilities, experiences a profound sense of joy and boundless energy while supporting their team during the tournament.This sentiment extends even to those who may not have the same physical mobility as others, including individuals who are paralyzed. In the context of empowering differently-abled individuals and making their lives more fulfilling during events like the World Cup, it's crucial to highlight the government's efforts and available resources. In 2022-23, the Department of Empowerment of Persons with Disabilities (DEPwD) received a significant budget allocation of Rs 1212.41 crore, reflecting a positive trend of increasing support for differently abled community. This financial boost indicates a growing recognition of the importance of inclusion and accessibility for all, regardless of physical abilities. Paralyzed people make a significant portion of the society that make most of all the opportunities given to them and utilize available resources to navigate through the events and find joy as enthusiastic audience. The Deendayal Disabled Rehabilitation Scheme (DDRS) is a vital initiative under the DEPwD that aims to promote voluntary action for persons with disabilities. This scheme provides essential support, rehabilitation services and assistive devices, contributing to a better quality of life for physically impaired individuals. These extraordinary individuals impart invaluable life lessons to us. They exemplify the resilience needed to overcome obstacles and demonstrate that no matter how insurmountable the challenges may seem, there is always a motivating force compelling us to rise above our problems. Moreover, it is the responsibility of those who possess physical capabilities to extend a helping hand to those in need, opening the doors of our hearts as wide as possible.",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
    ],
  },
  {
    name: "Comming Soon",
    blogs: [
      {
        name: "Comming Soon",
        pic: amp,
        data: "In the realm of sports, a world of excitement, celebration, and unity unfolds. Mega sports events, such as “The Cricket World Cup”, have the remarkable power to bring together billions of people from diverse backgrounds, transcending language barriers, cultural differences, and national boundaries. These events infuse an unparalleled level of energy and enthusiasm among fans of the game . The love for cricket is an undisputed passion, irrespective of one's personal abilities and circumstances. Every spectator, regardless of their physical capabilities, experiences a profound sense of joy and boundless energy while supporting their team during the tournament.This sentiment extends even to those who may not have the same physical mobility as others, including individuals who are paralyzed. In the context of empowering differently-abled individuals and making their lives more fulfilling during events like the World Cup, it's crucial to highlight the government's efforts and available resources. In 2022-23, the Department of Empowerment of Persons with Disabilities (DEPwD) received a significant budget allocation of Rs 1212.41 crore, reflecting a positive trend of increasing support for differently abled community. This financial boost indicates a growing recognition of the importance of inclusion and accessibility for all, regardless of physical abilities. Paralyzed people make a significant portion of the society that make most of all the opportunities given to them and utilize available resources to navigate through the events and find joy as enthusiastic audience. The Deendayal Disabled Rehabilitation Scheme (DDRS) is a vital initiative under the DEPwD that aims to promote voluntary action for persons with disabilities. This scheme provides essential support, rehabilitation services and assistive devices, contributing to a better quality of life for physically impaired individuals. These extraordinary individuals impart invaluable life lessons to us. They exemplify the resilience needed to overcome obstacles and demonstrate that no matter how insurmountable the challenges may seem, there is always a motivating force compelling us to rise above our problems. Moreover, it is the responsibility of those who possess physical capabilities to extend a helping hand to those in need, opening the doors of our hearts as wide as possible.",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
      {
        name: "Comming Soon",
        pic: amp,
        data: "inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi nesciunt reiciendis, inventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat explicabo hic tenetur saepe officiis consequuntur beatae ullam delectus aperiam, id maiores est ratione facilis dolorem consequatur maxime, temporibus nam aliquam totam, nobis voluptatum vel a. Similique corporis pariatur dolores necessitatibus ipsam fugiat modi, odit cumque molestias? Eum enim dignissimos incidunt excepturi ninventore commodi neque dolorem laborum dicta veniam quam asperiores. Iure natus vitae tempore, inventore labore animi rerum distinctio hicnderit dolore. Distinctio rerum ad, veritatis odit similique assumenda alias iure incidunt, neque autem aliquid necessitatibus quibusdam provident quod voluptates, aliquam deleniti eius sapiente! Ducimus laborum placeat ",
      },
    ],
  },
];
